# Generated by Django 4.1.7 on 2023-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="digital",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
